### ISSUE TITLE
fix: shrink the main article size

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#147]
The main article size on default template is too wide,
that is not good for reading.

We must shrink to a maximum 894px which is the recommended width for readability.

CSS
```css
.content-tags {
    gap: revert;
}
.content-tags li {
    background-color: revert;
    padding:2px;
    margin:0;
}
.content-tags li a {
    color: var(--pico-primary);
}

.content-tags li::before {
    content: "#";
    border: 0;
    position: revert;
    left: revert;
}

.header-menu li {
    padding: revert;
    padding-right: 16px;
}
.content-banner-image {
    height: 200px;
}


@media (min-width: 1280px) {
    :root {
      --pico-font-size: 118.75%;
    }
  }
@media (min-width: 1024px) {
    .container {
      max-width: 894px;
    }
  }
@media (min-width: 1280px) {
    .container {
        max-width: 894px;
    }
}
@media (min-width: 1536px) {
    .container {
        max-width: 894px;
    }
}
```
