### ISSUE TITLE
feat: assume author by default

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#148]
When there is an author on `marmite.yaml`

```yaml
authors:
    rochacbruno:
       ...
```

If not specified on articles, and `default_author: rochacbruno` is set, all articles will assume that author.

Change on `get_authors` function.
