### ISSUE TITLE
Custom static folders

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#207]
### Discussed in https://github.com/rochacbruno/marmite/discussions/206

<div type='discussions-op-text'>

<sup>Originally posted by **forresto** January 20, 2025</sup>
I have a small web toys at URLs like mysite.com/myapp. Is it possible to add custom static directories to be copied over? It wouldn't need to be templated, it would just work like the media directory.

```
myblog/
   |_ content/
         |_ about.md
         |_ hello-world.md
         |_ media/
             |_ myphoto.png
         |_ myapp/
             |_ index.html
             |_ myapp-creative-code-fun.js
```</div>

**Comment by rochacbruno** [comment]
The way this must work is:

On `marmite.yaml`

```yaml
extra:
  static_folders:  # relative to the input folder (root of project)
    - content/myapp
```

Then, marmite when copying static files to `output_folder` will also  copy the listed folders
