### ISSUE TITLE
Add `marmite` template to GitLab's built-in project templates

### ISSUE THREAD

**Issue by luxedo** [rochacbruno/marmite#216]
GitLab has several built-in project templates and they are [open for contribution](https://docs.gitlab.com/ee/development/project_templates/add_new_template.html).

Perhaps integrating it with [GitLab Pages](https://docs.gitlab.com/ee/user/project/pages/) and a simple CI/CD pipeline would make it very easy to build and host a `marmite` project.

If that's something interesting I'd be glad to take a look. I'm not familiar with `marmite` yet so I'd need some help specifying the requirements and the structure for this template.

**Comment by luxedo** [comment]
Nice! I'll take a look!

**Comment by luxedo** [comment]
I just created a repo from https://github.com/rochacbruno/blog and changed the pipeline to GitLab's CI/CD. Here's the new [repo](https://gitlab.com/luxedo/marmite)  and the `.gitlab-ci.yml` file:

```yaml
# The Docker image that will be used to build your app
image: rust:1.84.1
# Functions that should be executed before the build script is run
before_script:
  - "cargo install marmite  # 🫙"
pages:
  script:
    - "marmite . public --debug  # 🏗️"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
```

The rendered template blog is here: https://luxedo.gitlab.io/marmite/

As is, this GitLab template can be forked and will work fine. In order to include this in the GitLab's project template list there's still some things to do:
1. Update README.md to match the GitLab workflow
2. Create a PR to include the new template
3. Add template logo and description

Before proceeding with this process @rochacbruno would you like to own the GitLab's `marmite` template repo? I can also create an organization to make it neater. What do you think?
