### ISSUE TITLE
[feat] Comment block

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#49]
`marmite` will be agnostic in terms of comment system,

by default, no comment system will be available.

On `marmite.yam` there will be a `comment` config variable.

```yaml
comment:
  system: "disqus"
  id: "fsfsfsdf"
  extra_keys: ...
```

When comment exists, marmite will `{% include "comments.html" ignore missing %}`

There will be embedded comments.html supporting disqus, hatsu (activity pub), and some other popular system.

User can replace the template if needed to customize.
