### ISSUE TITLE
[feat] Feeds (ActivityPub)

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#8]
Feeds must be generated

- feed.rss
- /tag/tagname.rss
- feed.json
- /tag/feed.json

It is important to render the JSON feed so we can integrate with Hatsu https://hatsu.cli.rs/

**Comment by rochacbruno** [comment]
It must be possible to configure filters for `rss` feeds.

```
extra:
  feeds:
    dont_create:
      tags: foo
    filter_from_main_feed:
      tags: til, news
      tags_contains: journal 
      title__contains: diary
```

This will be used to filter out content from the main feed, those items would be accessible only on individual tag feed. 

Tag foo will not have a feed created
