### ISSUE TITLE
[feat] Add author card to the posts

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#83]
when

`marmite.yaml`
```yaml

  show_author_card: true
  authors:
    rochacbruno:
      name: Bruno Rocha
      avatar: ./media/rochacbruno.png
      bio: I am a person that writes text about things....
      links: [["Fedi", "https://go.rocha.social/@bruno"]]
    jondoe:
      ...    
```

Then on each post

```markdown
# Hello
This is the post text
```

The above, as doesn't specify an author, the first author of the authors list will be assumed and will show on template (default on top) a card showing the information:

![2024-10-25_16-51](https://github.com/user-attachments/assets/ff390135-5f7a-4e0a-a54a-ca004c7b65f0)

 (and also on lists but with a smaller size)

This will also require rendering a page `author/rochacbruno.html` using the `group.html` template and on that template there will be a list of author Bio and links.

If post has a different author, or even multiple authors then

```markdown
---
extra:
  authors: ["jondoe"]
---
# Hello
This 
```
